export enum OrmSubscriptionTier {
    FREE = 'FREE',
    PRO = 'PRO',
    AGENCY = 'AGENCY',
}

export enum OrmTemplateType {
    SHOWCASE = 'SHOWCASE',
    ECOMMERCE_ITEM = 'ECOMMERCE_ITEM',
    ECOMMERCE_SUBSCRIPTION = 'ECOMMERCE_SUBSCRIPTION',
}

export enum OrmRunnerTaskStatus {
    QUEUED = 'QUEUED',
    PROCESSING = 'PROCESSING',
    COMPLETED = 'COMPLETED',
    FAILED = 'FAILED',
}

export enum OrmRunnerTaskType {
    WEBSITE_GENERATION = 'WEBSITE_GENERATION',
    SOCIAL_MEDIA_CONTENT = 'SOCIAL_MEDIA_CONTENT',
    BLOG_POST_WRITING = 'BLOG_POST_WRITING',
}
